# Generated by Django 5.2 on 2025-06-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_name'),
        ('employment', '0004_school_pickleprofile_employeeeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='school',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='level',
            field=models.CharField(choices=[('GCSE', 'GCSE'), ('A-Level', 'A-Level'), ('BTEC', 'BTEC'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], default='GCSE', max_length=255),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.school'),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='skills',
            field=models.ManyToManyField(to='employment.jobskill'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='experience_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.location'),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.location'),
        ),
    ]
