# Generated by Django 5.2 on 2025-06-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_name'),
        ('employment', '0005_location_remove_employeeeducation_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickleprofile',
            name='overview_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
            ],
        ),
    ]
