# Generated by Django 5.2 on 2025-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_pickleprofile_overview_description_employeeinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickleprofile',
            name='cv_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickleprofile',
            name='education_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickleprofile',
            name='experience_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickleprofile',
            name='interests_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickleprofile',
            name='skills_completed',
            field=models.BooleanField(default=False),
        ),
    ]
