# Generated by Django 5.2 on 2025-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0007_pickleprofile_cv_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickleprofile',
            name='cv_blank',
            field=models.BooleanField(default=True),
        ),
    ]
